# Note that you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.
# Multiline strings are treated as verbose regular expressions by Black.
# Use [ ] to denote a significant space character.

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
# include = '\.pyi?$'
exclude = '''
# NOTE1: put files/dirs in between parentheses and seperate with a '|'
# NOTE2: to exclude a dir (e.g foo/bar) no prefix is required (just use add bar/). bar exludes foo/bar and bar.py
(
  # some common dirs to exclude
  # --------------------------------------
    .eggs
  | .git
  | .hg
  | .mypy_cache
  | .tox
  | .venv
  | _build/
  | buck-out/
  | build/
  | dist/
)
'''
